import Dashboard from "@/src/components/templates/dashboard/dashboard";

export const metadata = {
  title: "Create ddd App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <Dashboard>{children}</Dashboard>;
}
