import { DM_Sans } from "next/font/google";

const inter = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create  App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className=" " lang="en">
      <body className={[inter.className, ""]}>{children}</body>
    </html>
  );
}
